---
# CoreOS tasks file for sigio-newrelic-machineagent


- name: Create NewRelic group
  group: name="{{newrelic_group}}" state=present system=yes

- name: Create NewRelic user
  user: name="{{newrelic_user}}" group="{{newrelic_group}}" comment="New Relic monitoring daemon" state=present system=yes home="{{newrelic_home}}" shell=/sbin/nologin

- name: Create misc directories
  file: state=directory path="{{item}}" owner="{{newrelic_user}}" group="{{newrelic_group}}" mode=0600
  with_items:
    - "{{newrelic_etc}}"
    - "{{newrelic_log}}"
    - "{{newrelic_home}}"

- name: Fetch and extract newrelic tarball
  unarchive: copy=no src="{{newrelic_download_path}}/{{newrelic_download_file}}" dest="{{newrelic_home}}" owner=newrelic group=newrelic creates="{{newrelic_home}}/newrelic-sysmond-{{newrelic_version}}-linux"
  register: newrelic_upgraded

- name: Create symlinks to correct versions
  file: state=link src="{{newrelic_home}}/newrelic-sysmond-{{newrelic_version}}-linux/{{item.src}}" dest="{{item.dest}}"
  with_items:
    - { src: "daemon/nrsysmond.x64", dest: "{{newrelic_home}}/nrsysmond" }
    - { src: "scripts/nrsysmond-config", dest: "{{newrelic_home}}/nrsysmond-config" }
    - { src: "nrsysmond.cfg", dest: "{{newrelic_etc}}/nrsysmond.cfg" }
  when: newrelic_upgraded|changed

- name: Template systemd unit file
  template: src="newrelic-sysmond.j2" dest="/etc/systemd/system/newrelic-sysmond.service" owner=root group=root mode=0644
