---
# tasks file for sigio-newrelic-machineagent
# Currently only CentOS/RHEL 5/6/7

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: coreos.yml
  when: ansible_os_family == "CoreOS"

- name: Set license key
  lineinfile: dest=/etc/newrelic/nrsysmond.cfg line="license_key={{newrelic_licensekey}}" regexp="^license_key=" owner=root group=newrelic mode=0640
  when: newrelic_install_sysmond|bool
  tags:
    - newrelic
    - newrelic-agent
    - newrelic-license
  notify: reload-newrelic

- name: Enable/Start newrelic agent
  service: name={{item}} state=started enabled=yes
  with_items:
    - newrelic-sysmond
  when: newrelic_install_sysmond|bool
  tags:
    - newrelic
    - newrelic-agent

- name: Install NewRelic Java Agent
  copy: dest={{newrelic_javaagent_path}}/{{item}} src=newrelic/{{item}} owner=newrelic group=newrelic mode=0644
  with_items:
    - CHANGELOG
    - LICENSE
    - extension-example.xml
    - extension.xsd
    - newrelic-api.jar
    - newrelic-api-sources.jar
    - newrelic.jar
    - nrcerts
    - README.txt
  when: newrelic_install_javaagent|bool
  tags:
    - newrelic
    - newrelic-java

- name: Template NewRelic Java agent configuration
  template: src=newrelic.yml.j2 dest={{newrelic_javaagent_path}}/newrelic.yml owner=newrelic group=newrelic mode=0644
  when: newrelic_install_javaagent|bool
  tags:
    - newrelic
    - newrelic-java

